name: chandrasekhar
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  aryabhata:
    path: ../aryabhata
  ramanujan:
    path: ../ramanujan

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
